version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: smiles-spectrum-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/model:/app/backend/app/model:ro
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: smiles-spectrum-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    restart: unless-stopped
